name: wash_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  adaptive_theme: ^3.7.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dotted_decoration: ^2.0.0
  easy_localization: ^3.0.7+1
  easy_stepper: ^0.8.5+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  go_router: ^15.1.3
  google_maps_flutter: ^2.12.3
  intl_mobile_field: ^2.1.0
  intl_phone_field: ^3.2.0
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/font/
    - assets/translations/
    - assets/map/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Noor
      fonts:
        - asset: assets/font/NoorRegular.ttf
          weight: 400
        - asset: assets/font/NoorBold.ttf
          weight: 700
        - asset: assets/font/NoorLight.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils
  filename: app_images.dart
